package com.diary.superjournalapp.export;

import android.content.Context;
import android.text.Html;
import android.util.Log;

import com.diary.superjournalapp.dto.BulletEntryDetails;
import com.diary.superjournalapp.entity.Journal;
import com.diary.superjournalapp.entity.JournalCategories.BulletJournalEntity;
import com.diary.superjournalapp.entity.JournalCategories.DreamJournalEntity;
import com.diary.superjournalapp.entity.JournalCategories.GratitudeJournalEntity;
import com.diary.superjournalapp.entity.JournalCategories.ReflectiveJournalEntity;
import com.diary.superjournalapp.entity.Tag;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Plain text export implementation
 */
public class TxtExporter {
    
    private static final String TAG = "TxtExporter";
    private static final String DIVIDER = "─────────────────────────────────────────────────────────────";
    private static final String DOUBLE_DIVIDER = "═════════════════════════════════════════════════════════════";
    
    private Context context;
    
    public TxtExporter(Context context) {
        this.context = context;
    }
    
    /**
     * Export a journal to plain text format
     * 
     * @param journal The journal metadata
     * @param content The journal content (entity)
     * @param tags Associated tags
     * @param options Export options
     * @return TXT data as byte array
     */
    public byte[] exportToTxt(Journal journal, Object content,
                             List<Tag> tags, ExportOptions options) {
        try {
            StringBuilder txt = new StringBuilder();
            
            // Header
            txt.append(DOUBLE_DIVIDER).append("\n");
            txt.append("DiaryVerse Journal Export\n");
            txt.append(DOUBLE_DIVIDER).append("\n\n");
            
            // Title
            txt.append("Title: ").append(journal.getTitle()).append("\n");
            
            // Category
            txt.append("Category: ").append(journal.getJournalCategory()).append("\n");
            
            // Date
            SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM d, yyyy 'at' h:mm a", 
                                                              Locale.getDefault());
            String dateStr = dateFormat.format(journal.getJournalCreatedOn());
            txt.append("Date: ").append(dateStr).append("\n");
            
            // Tags
            if (options.isIncludeTags() && tags != null && !tags.isEmpty()) {
                txt.append("Tags: ");
                for (int i = 0; i < tags.size(); i++) {
                    txt.append("#").append(tags.get(i).getName());
                    if (i < tags.size() - 1) {
                        txt.append(" ");
                    }
                }
                txt.append("\n");
            }
            
            txt.append("\n").append(DIVIDER).append("\n\n");
            
            // Content
            String journalContent = extractContent(content);
            if (journalContent != null && !journalContent.isEmpty()) {
                // Strip HTML and convert to plain text
                String plainText = Html.fromHtml(journalContent, Html.FROM_HTML_MODE_LEGACY).toString();
                txt.append(plainText).append("\n");
            }
            
            // Metadata
            if (options.isIncludeMetadata()) {
                txt.append("\n").append(DIVIDER).append("\n\n");
                txt.append("Metadata:\n");
                txt.append("- Journal ID: ").append(journal.getJournalId()).append("\n");
                
                // Word count
                if (journalContent != null) {
                    int wordCount = journalContent.split("\\s+").length;
                    txt.append("- Word Count: ").append(wordCount).append("\n");
                }
                
                // Export date
                SimpleDateFormat exportDateFormat = new SimpleDateFormat("MMMM d, yyyy 'at' h:mm a", 
                                                                        Locale.getDefault());
                String exportDate = exportDateFormat.format(new java.util.Date());
                txt.append("- Exported: ").append(exportDate).append("\n");
            }
            
            // Footer
            txt.append("\n").append(DOUBLE_DIVIDER).append("\n");
            txt.append("Generated by DiaryVerse\n");
            txt.append("https://play.google.com/store/apps/details?id=com.diary.superjournalapp\n");
            txt.append(DOUBLE_DIVIDER).append("\n");
            
            return txt.toString().getBytes(StandardCharsets.UTF_8);
            
        } catch (Exception e) {
            Log.e(TAG, "Failed to create TXT", e);
            return null;
        }
    }
    
    /**
     * Extract content string from journal entity
     */
    private String extractContent(Object content) {
        if (content instanceof ReflectiveJournalEntity) {
            return ((ReflectiveJournalEntity) content).getJournalContent();
        } else if (content instanceof GratitudeJournalEntity) {
            return ((GratitudeJournalEntity) content).getJournalContent();
        } else if (content instanceof DreamJournalEntity) {
            return ((DreamJournalEntity) content).getJournalContent();
        } else if (content instanceof BulletJournalEntity) {
            return formatBulletJournalContent((BulletJournalEntity) content);
        }
        return null;
    }
    
    /**
     * Format bullet journal tasks into readable text
     */
    private String formatBulletJournalContent(BulletJournalEntity bulletJournal) {
        try {
            Gson gson = new Gson();
            Type listType = new TypeToken<ArrayList<BulletEntryDetails>>() {}.getType();
            ArrayList<BulletEntryDetails> tasks = gson.fromJson(
                bulletJournal.getTaskListJson(), listType);
            
            if (tasks == null || tasks.isEmpty()) {
                return "No tasks in this bullet journal.";
            }
            
            StringBuilder sb = new StringBuilder();
            sb.append("Tasks:\n\n");
            
            for (BulletEntryDetails task : tasks) {
                String checkbox = task.getIsTaskDone() ? "[x]" : "[ ]";
                sb.append(checkbox)
                  .append(" ")
                  .append(task.getTaskName())
                  .append("\n");
            }
            
            return sb.toString();
            
        } catch (Exception e) {
            Log.e(TAG, "Failed to parse bullet journal", e);
            return "Error parsing tasks.";
        }
    }
}
